#!/bin/tcsh

# rm list_of_Bkgfiles/*.root
rm output_log/condor_*

# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_QQ_HT-600ToInf_v3/
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_QQ_HT-600ToInf_v3

# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-80to120_MuEnr_v3/ 
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-120to170_MuEnr_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-170to300_MuEnr_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-300to470_MuEnr_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-470to600_MuEnr_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-600to800_MuEnr_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-800to1000_MuEnr_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-1000toInf_MuEnr_v3/

# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-70To100_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-100To200_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-200To400_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-400To600_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-600To800_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-800To1200_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-1200To2500_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-2500ToInf_v3/

# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_TTbar_v3/

# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-70To100_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-100To200_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-200To400_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-400To600_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-600To800_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-800To1200_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-1200To2500_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-2500ToInf_v3/

# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_s-channel_4f_leptonDecays_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_t-channel_antitop_4f_inclusiveDecays_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_t-channel_top_4f_inclusiveDecays_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_tW_antitop_5f_inclusiveDecays_v3/
# eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_tW_top_5f_inclusiveDecays_v3/ 

#eosrm -r /eos/uscms/store/user/achhetri/PhaseII_MainTree/JobsCheckFile_v3/


# eosls  /eos/uscms/store/user/achhetri/

# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-80to120_MuEnr_v3 
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-120to170_MuEnr_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-170to300_MuEnr_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-300to470_MuEnr_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-470to600_MuEnr_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-600to800_MuEnr_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-800to1000_MuEnr_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_QCD_Pt-1000toInf_MuEnr_v3

# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-70To100_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-100To200_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-200To400_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-400To600_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-600To800_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-800To1200_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-1200To2500_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_WJets_LNu_HT-2500ToInf_v3

# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_TTbar_v3

# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-70To100_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-100To200_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-200To400_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-400To600_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-600To800_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-800To1200_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-1200To2500_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/Bkg_DYJetsToLL_M-50_HT-2500ToInf_v3

# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_s-channel_4f_leptonDecays_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_t-channel_antitop_4f_inclusiveDecays_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_t-channel_top_4f_inclusiveDecays_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_tW_antitop_5f_inclusiveDecays_v3
# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/ST_tW_top_5f_inclusiveDecays_v3 

# eosmkdir /eos/uscms/store/user/achhetri/PhaseII_MainTree/JobsCheckFile_v3


cd /eos/user/a/achhetri/Tprime_PhaseIII/Analyzed_NANO_file_via_Condor/Background_Samples_UL17/

rm -r UL17_TTbar_Files
rm -r UL17_QCD_MuEnr_Files
rm -r UL17_Wjets_To_LNu_Files
rm -r UL17_DYjetsTo_LL_Files
rm -r UL17_SingleTop_Files

mkdir UL17_TTbar_Files/ 
mkdir UL17_QCD_MuEnr_Files/
mkdir UL17_Wjets_To_LNu_Files/
mkdir UL17_DYjetsTo_LL_Files/
mkdir UL17_SingleTop_Files/

cd /afs/cern.ch/work/a/achhetri/Tprime-tH-lvb4q_PhaseIII/CMSSW_10_6_8/src/Phase_III_Analysis_with_NanoAOD/NANO_AOD_Analyzer


cd ../../../../

rm CMSSW_10_68.tgz

tar  --exclude=tmp --exclude=.git --exclude=DAS_Root --exclude=PhysicsTools --exclude=WTopScalefactorProducer --exclude=MuonReferenceEfficiencies-master-EfficienciesStudies-UL2016_postVFP-DEN_TrackerMuons-rootfiles --exclude=MuonReferenceEfficiencies-master-EfficienciesStudies-UL2018-DEN_TrackerMuons-rootfiles --exclude=NANOAOD --exclude=List_of_NANO_AOD_paths --exclude=Data_Files_Path_NaNoAOD --exclude=Large_Data_Files_Listing --exclude=data_output_log -zcvf CMSSW_10_68.tgz CMSSW_10_6_8


xrdcp -f CMSSW_10_68.tgz root://eosuser.cern.ch//eos/user/a/achhetri/.


ls -ltrh
cd -

# condor_submit Tb_tH_LH_M1000_merged_test.jdl
# # condor_submit test.jdl
# # 
# condor_q

# eosls -ltrh /eos/uscms/store/user/achhetri/PhaseII_MainTree/Background_v3_Samples/
# ls -ltrh


# list of jobs
# Queue filename matching files list_of_Bkgfiles/Bkg_QCD_Pt*.txt
# Queue filename matching files list_of_Bkgfiles/Bkg_WJets_*.txt
# Queue filename matching files list_of_Bkgfiles/Bkg_TTbar_*.txt
# Queue filename matching files list_of_Bkgfiles/Bkg_DYJetsToLL_*.txt
# Queue filename matching files list_of_Bkgfiles/ST_*.txt